// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CompareBackups(arg1, arg2) {
  return window['go']['main']['App']['CompareBackups'](arg1, arg2);
}

export function CompareDiff(arg1) {
  return window['go']['main']['App']['CompareDiff'](arg1);
}

export function DeleteAuditRule(arg1) {
  return window['go']['main']['App']['DeleteAuditRule'](arg1);
}

export function DeleteCredential(arg1) {
  return window['go']['main']['App']['DeleteCredential'](arg1);
}

export function DeleteDevice(arg1) {
  return window['go']['main']['App']['DeleteDevice'](arg1);
}

export function DeletePlaybook(arg1) {
  return window['go']['main']['App']['DeletePlaybook'](arg1);
}

export function DeleteScheduledJob(arg1) {
  return window['go']['main']['App']['DeleteScheduledJob'](arg1);
}

export function ExportBackupsZip(arg1) {
  return window['go']['main']['App']['ExportBackupsZip'](arg1);
}

export function ExportScanToExcel(arg1) {
  return window['go']['main']['App']['ExportScanToExcel'](arg1);
}

export function GetAuditLogs(arg1) {
  return window['go']['main']['App']['GetAuditLogs'](arg1);
}

export function GetAuditRules() {
  return window['go']['main']['App']['GetAuditRules']();
}

export function GetBackupContent(arg1) {
  return window['go']['main']['App']['GetBackupContent'](arg1);
}

export function GetBackups(arg1) {
  return window['go']['main']['App']['GetBackups'](arg1);
}

export function GetCredentials() {
  return window['go']['main']['App']['GetCredentials']();
}

export function GetDevice(arg1) {
  return window['go']['main']['App']['GetDevice'](arg1);
}

export function GetDevices() {
  return window['go']['main']['App']['GetDevices']();
}

export function GetLastScanDevices() {
  return window['go']['main']['App']['GetLastScanDevices']();
}

export function GetLogFileContent(arg1) {
  return window['go']['main']['App']['GetLogFileContent'](arg1);
}

export function GetLogFiles() {
  return window['go']['main']['App']['GetLogFiles']();
}

export function GetPlaybooks() {
  return window['go']['main']['App']['GetPlaybooks']();
}

export function GetScheduledJobs() {
  return window['go']['main']['App']['GetScheduledJobs']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetTopology() {
  return window['go']['main']['App']['GetTopology']();
}

export function RunAudit(arg1) {
  return window['go']['main']['App']['RunAudit'](arg1);
}

export function RunBackup(arg1) {
  return window['go']['main']['App']['RunBackup'](arg1);
}

export function RunPlaybook(arg1) {
  return window['go']['main']['App']['RunPlaybook'](arg1);
}

export function RunSSHCommands(arg1) {
  return window['go']['main']['App']['RunSSHCommands'](arg1);
}

export function RunTerminalCommand(arg1, arg2) {
  return window['go']['main']['App']['RunTerminalCommand'](arg1, arg2);
}

export function SaveAuditRule(arg1) {
  return window['go']['main']['App']['SaveAuditRule'](arg1);
}

export function SaveCredential(arg1) {
  return window['go']['main']['App']['SaveCredential'](arg1);
}

export function SaveDevice(arg1) {
  return window['go']['main']['App']['SaveDevice'](arg1);
}

export function SavePlaybook(arg1) {
  return window['go']['main']['App']['SavePlaybook'](arg1);
}

export function SaveScheduledJob(arg1) {
  return window['go']['main']['App']['SaveScheduledJob'](arg1);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function ScanNetwork(arg1) {
  return window['go']['main']['App']['ScanNetwork'](arg1);
}

export function StopAllTasks() {
  return window['go']['main']['App']['StopAllTasks']();
}

export function TestDeviceConnection(arg1) {
  return window['go']['main']['App']['TestDeviceConnection'](arg1);
}

export function TestSNMPHost(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['TestSNMPHost'](arg1, arg2, arg3, arg4);
}

export function ToggleScheduledJob(arg1, arg2) {
  return window['go']['main']['App']['ToggleScheduledJob'](arg1, arg2);
}
