// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {diff} from '../models';
import {main} from '../models';
import {models} from '../models';
import {topology} from '../models';
import {audit} from '../models';
import {playbook} from '../models';
import {ssh} from '../models';

export function ClearInventory():Promise<void>;

export function CompareBackups(arg1:string,arg2:string):Promise<diff.DiffResult>;

export function CompareDiff(arg1:main.DiffRequest):Promise<diff.DiffResult>;

export function DeleteAuditRule(arg1:string):Promise<void>;

export function DeleteCredential(arg1:string):Promise<void>;

export function DeleteDevice(arg1:string):Promise<void>;

export function DeletePlaybook(arg1:string):Promise<void>;

export function DeleteScheduledJob(arg1:string):Promise<void>;

export function ExportBackupsZip(arg1:Array<string>):Promise<string>;

export function ExportDiffHTML(arg1:main.DiffRequest,arg2:string,arg3:string):Promise<string>;

export function ExportScanToExcel(arg1:Array<string>):Promise<string>;

export function GetAuditLogs(arg1:main.AuditLogQuery):Promise<Array<models.AuditLog>>;

export function GetAuditRules():Promise<Array<models.AuditRule>>;

export function GetBackupContent(arg1:string):Promise<string>;

export function GetBackups(arg1:string):Promise<Array<models.Backup>>;

export function GetCredentials():Promise<Array<models.CredentialView>>;

export function GetDevice(arg1:string):Promise<models.Device>;

export function GetDevices():Promise<Array<models.Device>>;

export function GetDevicesByIPs(arg1:Array<string>):Promise<Array<models.Device>>;

export function GetLastScanDevices():Promise<Array<models.Device>>;

export function GetLogFileContent(arg1:string):Promise<string>;

export function GetLogFiles():Promise<Array<string>>;

export function GetPlaybooks():Promise<Array<models.Playbook>>;

export function GetScheduledJobs():Promise<Array<models.ScheduledJob>>;

export function GetSettings():Promise<main.AppSettings>;

export function GetTopology():Promise<topology.Graph>;

export function RunAudit(arg1:Array<string>):Promise<Array<audit.AuditReport>>;

export function RunAuditFiltered(arg1:Array<string>,arg2:Array<string>):Promise<Array<audit.AuditReport>>;

export function RunBackup(arg1:main.BackupRequest):Promise<Array<models.Backup>>;

export function RunPlaybook(arg1:main.PlaybookRunRequest):Promise<Array<playbook.ExecutionResult>>;

export function RunSSHCommands(arg1:main.SSHCommandRequest):Promise<Array<ssh.Result>>;

export function RunScheduledJobNow(arg1:string):Promise<void>;

export function RunTerminalCommand(arg1:string,arg2:string):Promise<string>;

export function SaveAuditRule(arg1:models.AuditRule):Promise<models.AuditRule>;

export function SaveCredential(arg1:main.CredentialInput):Promise<models.CredentialView>;

export function SaveDevice(arg1:models.Device):Promise<models.Device>;

export function SavePlaybook(arg1:models.Playbook):Promise<models.Playbook>;

export function SaveScheduledJob(arg1:models.ScheduledJob):Promise<models.ScheduledJob>;

export function SaveSettings(arg1:main.AppSettings):Promise<void>;

export function ScanNetwork(arg1:main.ScanRequest):Promise<Array<models.Device>>;

export function StopAllTasks():Promise<string>;

export function TestDeviceConnection(arg1:string):Promise<Record<string, any>>;

export function TestSNMPHost(arg1:string,arg2:string,arg3:string,arg4:number):Promise<main.SNMPTestResult>;

export function ToggleScheduledJob(arg1:string,arg2:boolean):Promise<void>;
